#!/usr/bin/env python
"""Parity scoreboard for topologic_fast vs topologicpy.

Produces a measurable, living gap report with two halves:

1. **Structural coverage** — for each in-scope topologicpy module/class, which of
   its public methods exist on the matching ``topologic_fast`` class (name-level).
2. **Differential results** — runs the ``tests/parity`` case corpus through both
   the reference (``topologic_core``) and candidate (``topologic_fast``) kernels
   and tallies how many produce identical results.

Writes ``PARITY.md`` at the repo root and prints a one-line summary. Run:

    .venv/bin/python tools/parity/api_diff.py
"""
from __future__ import annotations

import importlib
import inspect
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# topologicpy module -> class name. These are the in-scope drop-in targets: the
# core topology primitives + the data/graph classes that need the kernel.
IN_SCOPE = [
    "Vertex", "Edge", "Wire", "Face", "Shell", "Cell", "CellComplex", "Cluster",
    "Topology", "Dictionary", "Graph", "Vector", "Matrix", "Grid",
    "Aperture", "Context",
]

# Pure-Python helper modules in scope (informational — tracked separately).
HELPERS = ["Sun", "CSG", "Color", "Grid", "Matrix", "Vector", "Honeybee", "EnergyModel"]


def _topologicpy_methods(class_name):
    """Public static-method names defined on a topologicpy class, or None."""
    try:
        mod = importlib.import_module(f"topologicpy.{class_name}")
        cls = getattr(mod, class_name)
    except Exception:
        return None
    names = set()
    for name, member in vars(cls).items():
        if name.startswith("_"):
            continue
        # Exclude deprecated aliases (e.g. "Transform_old") — not part of the
        # real API surface a drop-in must reproduce.
        if name.endswith("_old"):
            continue
        if isinstance(member, staticmethod) or inspect.isfunction(member):
            names.add(name)
    return names


def _fast_methods(class_name):
    """Public method names on the matching topologic_fast class, or None."""
    import topologic_fast as tf
    cls = getattr(tf, class_name, None)
    if cls is None:
        return None
    return {n for n in dir(cls) if not n.startswith("_")}


def structural_report():
    rows = []
    total_ref = total_present = 0
    for name in IN_SCOPE:
        ref = _topologicpy_methods(name)
        fast = _fast_methods(name)
        if ref is None:
            rows.append((name, "—", "topologicpy module not found", []))
            continue
        if fast is None:
            rows.append((name, f"0/{len(ref)}", "no topologic_fast class", sorted(ref)))
            total_ref += len(ref)
            continue
        present = ref & fast
        missing = sorted(ref - fast)
        rows.append((name, f"{len(present)}/{len(ref)}", "", missing))
        total_ref += len(ref)
        total_present += len(present)
    pct = (100.0 * total_present / total_ref) if total_ref else 0.0
    return rows, total_present, total_ref, pct


def differential_report():
    """Run the parity corpus through both kernels; return (match, diverge, errors, details)."""
    sys.path.insert(0, os.path.join(REPO_ROOT, "tests", "parity"))
    try:
        import kernels  # type: ignore
        import cases  # type: ignore
        import compare  # type: ignore
    except Exception as e:
        return None, None, None, [f"could not import parity corpus: {e}"]
    try:
        core_k, fast_k = kernels.CoreKernel(), kernels.FastKernel()
    except Exception as e:
        return None, None, None, [f"could not build kernels: {e}"]
    match = diverge = errors = 0
    details = []
    for case_name, fn, xfail_reason in cases.CASES:
        try:
            ok, diffs = compare.compare(fn(core_k), fn(fast_k))
        except Exception as e:
            errors += 1
            details.append((case_name, "ERROR", str(e)))
            continue
        if ok:
            match += 1
            details.append((case_name, "match", ""))
        else:
            diverge += 1
            tag = "known-gap" if xfail_reason else "REGRESSION"
            details.append((case_name, tag, "; ".join(diffs)))
    return match, diverge, errors, details


def write_report():
    rows, present, ref_total, pct = structural_report()
    match, diverge, errors, details = differential_report()

    lines = []
    lines.append("# topologic_fast ↔ topologicpy parity scoreboard")
    lines.append("")
    lines.append("_Auto-generated by `tools/parity/api_diff.py`. Do not edit by hand._")
    lines.append("")
    lines.append("## Structural coverage (in-scope topologicpy methods present on topologic_fast)")
    lines.append("")
    lines.append(f"**Overall: {present}/{ref_total} methods ({pct:.1f}%)**")
    lines.append("")
    lines.append("| Class | Coverage | Note |")
    lines.append("|---|---|---|")
    for name, cov, note, _missing in rows:
        lines.append(f"| {name} | {cov} | {note} |")
    lines.append("")
    lines.append("### Missing methods per class")
    lines.append("")
    for name, cov, note, missing in rows:
        if missing:
            lines.append(f"- **{name}** ({cov}): " + ", ".join(f"`{m}`" for m in missing))
    lines.append("")
    lines.append("## Differential results (same operation on both kernels)")
    lines.append("")
    if match is None:
        lines.append("Could not run differential corpus:")
        for d in details:
            lines.append(f"- {d}")
    else:
        lines.append(f"**{match} match, {diverge} diverge, {errors} error** "
                     f"(of {match + diverge + errors} cases)")
        lines.append("")
        lines.append("| Case | Result | Detail |")
        lines.append("|---|---|---|")
        for case_name, tag, detail in details:
            detail = (detail[:90] + "…") if len(detail) > 90 else detail
            lines.append(f"| {case_name} | {tag} | {detail} |")
    lines.append("")

    out_path = os.path.join(REPO_ROOT, "PARITY.md")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return out_path, present, ref_total, pct, match, diverge, errors


def main():
    out_path, present, ref_total, pct, match, diverge, errors = write_report()
    print(f"Wrote {out_path}")
    print(f"Structural coverage: {present}/{ref_total} ({pct:.1f}%)")
    if match is not None:
        print(f"Differential: {match} match / {diverge} diverge / {errors} error")


if __name__ == "__main__":
    main()
