#!/usr/bin/env python
"""Generate ROADMAP.md — a phased, data-driven burn-down of topologicpy parity.

For every in-scope topologicpy method it determines one of three states:

  - [x] done      — present on the matching topologic_fast class AND referenced
                    by a parity test (verified).
  - [~] present   — present on topologic_fast but not yet covered by a test.
  - [ ] todo      — not implemented on topologic_fast.

Methods are grouped into phases by effort/value so they can be burned down
systematically. Run:

    .venv/bin/python tools/parity/roadmap.py
"""
from __future__ import annotations

import importlib
import inspect
import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Phase -> list of topologicpy class/module names (those with a tf counterpart
# get a per-method checklist; the rest are whole-module TODOs).
PHASES = [
    ("Phase A — Pure-math & data helpers",
     "Fast: pure Python via _pyhelpers / thin Rust. No geometry kernel.",
     ["Vector", "Matrix", "Grid", "Dictionary"]),
    ("Phase B — Core topology primitives",
     "Mix of pure-Rust (hot: readers/measures/constructors) and thin Python (cold tail).",
     ["Vertex", "Edge", "Wire", "Face", "Shell", "Cell", "CellComplex", "Cluster"]),
    ("Phase C — Topology dispatcher",
     "The 156-method hub: navigation/transform done; remaining = I/O (BREP/OBJ/JSON), "
     "analysis, booleans (Slice/Impose/Imprint), selectors.",
     ["Topology"]),
    ("Phase D — Graph analytics",
     "A full graph-analytics library (centralities, communities, flows, isomorphism). "
     "Real algorithm work; tf.Graph already has a base.",
     ["Graph"]),
    ("Phase E — Kernel features: apertures & contexts",
     "Missing kernel concepts (hosted sub-topologies + parametric contexts). "
     "Needs core Rust work before the 2 thin classes are meaningful.",
     ["Aperture", "Context"]),
    ("Phase F — Helper applications",
     "Pure-Python apps composing the primitives. Sun & EnergyModel already ported.",
     ["Sun", "CSG", "Color", "Helper", "EnergyModel", "Honeybee", "Plotly"]),
]

# Modules already delivered as standalone tf.* Python modules (not class-diffed).
DONE_MODULES = {"Sun", "EnergyModel"}


def _tpy_methods(name):
    try:
        cls = getattr(importlib.import_module(f"topologicpy.{name}"), name)
    except Exception:
        return None
    out = set()
    for n, v in vars(cls).items():
        if n.startswith("_") or n.endswith("_old"):
            continue
        if isinstance(v, staticmethod) or inspect.isfunction(v):
            out.add(n)
    return out


def _tf_methods(name):
    import topologic_fast as tf
    cls = getattr(tf, name, None)
    if cls is None:
        return None
    return {n for n in dir(cls) if not n.startswith("_")}


def _verified_pairs():
    """(Class, Method) pairs referenced by any parity/unit test (heuristic)."""
    pairs = set()
    pat = re.compile(r"\b(?:tf\.)?([A-Z][A-Za-z]+)\.([A-Za-z_][A-Za-z0-9_]*)\s*\(")
    for root in (os.path.join(REPO_ROOT, "tests"),):
        for dirpath, _dirs, files in os.walk(root):
            for f in files:
                if not f.endswith(".py"):
                    continue
                try:
                    text = open(os.path.join(dirpath, f)).read()
                except Exception:
                    continue
                for m in pat.finditer(text):
                    pairs.add((m.group(1), m.group(2)))
    return pairs


def generate():
    verified = _verified_pairs()
    lines = ["# topologic_fast → topologicpy parity ROADMAP",
             "",
             "_Auto-generated by `tools/parity/roadmap.py`. Burn-down checklist; do not edit by hand._",
             "",
             "Legend: `[x]` done (present + tested) · `[~]` present, untested · `[ ]` todo (not implemented)",
             ""]

    grand_total = grand_done = grand_present = 0
    phase_summ = []

    body = []
    for title, blurb, names in PHASES:
        body.append(f"## {title}")
        body.append("")
        body.append(f"_{blurb}_")
        body.append("")
        p_total = p_done = p_present = 0
        for name in names:
            tpy = _tpy_methods(name)
            if tpy is None:
                body.append(f"### {name} — topologicpy module not found")
                body.append("")
                continue
            total = len(tpy)
            if name in DONE_MODULES:
                body.append(f"### {name} — ✅ delivered as a standalone tf.{name} module ({total} methods)")
                body.append("")
                p_total += total
                p_done += total
                grand_total += total
                grand_done += total
                continue
            tf_set = _tf_methods(name) or set()
            done = sorted(m for m in tpy if m in tf_set and ((name, m) in verified or ("tf", m) in verified))
            present = sorted(m for m in tpy if m in tf_set and m not in done)
            todo = sorted(m for m in tpy if m not in tf_set)
            p_total += total
            p_done += len(done)
            p_present += len(present)
            grand_total += total
            grand_done += len(done)
            grand_present += len(present)
            body.append(f"### {name} — {len(done)} done / {len(present)} present / {len(todo)} todo "
                        f"(of {total})")
            body.append("")
            for m in done:
                body.append(f"- [x] `{name}.{m}`")
            for m in present:
                body.append(f"- [~] `{name}.{m}`")
            for m in todo:
                body.append(f"- [ ] `{name}.{m}`")
            body.append("")
        phase_summ.append((title, p_done, p_present, p_total))

    # Header summary table.
    lines.append("## Status")
    lines.append("")
    pct = 100.0 * (grand_done + grand_present) / grand_total if grand_total else 0
    lines.append(f"**{grand_done} done · {grand_present} present-untested · "
                 f"{grand_total - grand_done - grand_present} todo · "
                 f"{grand_total} total ({pct:.0f}% present)**")
    lines.append("")
    lines.append("| Phase | done | present | total |")
    lines.append("|---|---|---|---|")
    for title, d, pr, tot in phase_summ:
        lines.append(f"| {title} | {d} | {pr} | {tot} |")
    lines.append("")

    out = os.path.join(REPO_ROOT, "ROADMAP.md")
    with open(out, "w") as f:
        f.write("\n".join(lines + body) + "\n")
    return out, grand_done, grand_present, grand_total


if __name__ == "__main__":
    path, done, present, total = generate()
    print(f"Wrote {path}")
    print(f"{done} done / {present} present-untested / {total - done - present} todo / {total} total")
